version: "3.7"

x-volumes: &infra-volumes
  - ~/.bash_history:/root/.bash_history
  - .:/infra

services:
  yc-infra:
    build: .
    env_file:
      - .env
      - secrets.env
    stdin_open: true
    tty: true
    volumes: *infra-volumes
